### ISSUE TITLE
want to add all post to feed page without following

### ISSUE THREAD

**Issue by biwiwijaya** [Edenik/Flutter-Instagram-Clone#1]
awesome work, sir..
but can you help me, how to show all post without following in feed page?

**Comment by Edenik** [comment]
Add this function to DatabaseService:

`  static Future<List<Post>> getAllFeedPosts() async {
    List<Post> allPosts = [];

    QuerySnapshot usersSnapshot = await usersRef.getDocuments();

    for (var userDoc in usersSnapshot.documents) {
      QuerySnapshot feedSnapshot = await postsRef
          .document(userDoc.documentID)
          .collection('userPosts')
          .orderBy('timestamp', descending: true)
          .getDocuments();

      for (var postDoc in feedSnapshot.documents) {
        Post post = Post.fromDoc(postDoc);
        allPosts.add(post);
      }
    }
    return allPosts;
  }`


I reccommend to not use this function, it'll cost a lot of requests.
