### ISSUE TITLE
utilities/repo_const.dart file is missing

### ISSUE THREAD

**Issue by HassamTalha** [Edenik/Flutter-Instagram-Clone#10]

**Comment by waqas8919** [comment]
utilities/repo_const.dart file is missing where is that file,its not included in project please let us know how to solve this or include the file please.thanks

**Comment by riveraj33** [comment]
Hello. Where can we get this file?

**Comment by dehaoz20** [comment]
where to get this utilities/repo_const.dart file, anyone have this file please share it many thanks

**Comment by Edenik** [comment]
Have a look at this issue:
[#2](https://github.com/Edenik/InstaDart-Flutter-Instagram-Clone/issues/2)
