### ISSUE TITLE
Undefined Name kAdminUID Error

### ISSUE THREAD

**Issue by dhiru2** [Edenik/Flutter-Instagram-Clone#11]
When i run the project in my vs code editor then i have error like that .

Undefined Name kAdminUID In Dart Analytics.

**Comment by Edenik** [comment]
Have a look at this issue:
[#2](https://github.com/Edenik/InstaDart-Flutter-Instagram-Clone/issues/2)

**Comment by dhiru2** [comment]
Sir I'm user your code to my app for .
Commercial use
 Modification
 Distribution
 Private use. Tell me 
Thanks Sir
