### ISSUE TITLE
Getting error on kAdminUId and GiphyApiKey

### ISSUE THREAD

**Issue by swaraj961** [Edenik/Flutter-Instagram-Clone#2]
Hi man your project looks super awesome I was testing it on local but I'm facing some issues while locally running it can you help me resolve my issues.

Thanks, regards
swaraj

**Comment by Edenik** [comment]
You should add a constants file with:
kAdminUid - The User ID of the admin,
GiphyApiKey  - u should get a giphy developer api key and use it

**Comment by swaraj961** [comment]
> You should add a constants file with:
> kAdminUid - The User ID of the admin,
> GiphyApiKey - u should get a giphy developer api key and use it

Yup i did that after i go through the code i got it, 
Also love your app, i wish if you could upload a tutorial on this anyway great work 🙌🏻🔥

**Comment by EjazAmir** [comment]
kAdminUid what exactly it is? Can you bit explain about this.

**Comment by Edenik** [comment]
> kAdminUid what exactly it is? Can you bit explain about this.

kAdminUid - The User ID of the admin,
GiphyApiKey - u should get a giphy developer api key and use it

**Comment by jonnaah** [comment]
Hi, where can I get the admin ID?

**Comment by jonnaah** [comment]
> > kAdminUid what exactly it is? Can you bit explain about this.
> 
> kAdminUid - The User ID of the admin,
> GiphyApiKey - u should get a giphy developer api key and use it

Hi, where can I get the admin ID?

**Comment by Edenik** [comment]
> > > kAdminUid what exactly it is? Can you bit explain about this.
> > 
> > 
> > kAdminUid - The User ID of the admin,
> > GiphyApiKey - u should get a giphy developer api key and use it
> 
> Hi, where can I get the admin ID?

Admin ID is the ID of your user.

**Comment by jonnaah** [comment]
> > > > kAdminUid what exactly it is? Can you bit explain about this.
> > > 
> > > 
> > > kAdminUid - The User ID of the admin,
> > > GiphyApiKey - u should get a giphy developer api key and use it
> > 
> > 
> > Hi, where can I get the admin ID?
> 
> Admin ID is the ID of your user.

How I type the id and is it "@username" or "username". Do I have to replace "kAdminUid" or write my username after the AdminUid with "="?

**Comment by Edenik** [comment]
> > > > > kAdminUid what exactly it is? Can you bit explain about this.
> > > > 
> > > > 
> > > > kAdminUid - The User ID of the admin,
> > > > GiphyApiKey - u should get a giphy developer api key and use it
> > > 
> > > 
> > > Hi, where can I get the admin ID?
> > 
> > 
> > Admin ID is the ID of your user.
> 
> How I type the id and is it "@username" or "username". Do I have to replace "kAdminUid" or write my username after the AdminUid with "="?

You should create 2 constants - 
const kAdminUId = 'the user id of the first user / admin user';
const kGiphyApiKey = 'giphy api key';

**Comment by FasihCodes** [comment]
I am getting error on package called "instagram/utilities/repo_const.dart" and i don't know why and secondly the error on "kAdminUId". Please help me in solving these errors. I will be very thankful and tell me what to put in "kAdminUId".
