### ISSUE TITLE
'package:instagram/utilities/repo_const.dart' doesn't exsist

### ISSUE THREAD

**Issue by jonnaah** [Edenik/Flutter-Instagram-Clone#8]
Target of URI doesn't exist: 'package:instagram/utilities/repo_const.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

**Comment by ahraf111** [comment]
Facing the same issue. can someone help me out with this error.

**Comment by Edenik** [comment]
> Target of URI doesn't exist: 'package:instagram/utilities/repo_const.dart'.
> Try creating the file referenced by the URI, or Try using a URI for a file that does exist.



> Facing the same issue. can someone help me out with this error.

Have a look at this issue:
https://github.com/Edenik/InstaDart-Flutter-Instagram-Clone/issues/2
