### ISSUE TITLE
Posts not showing on feed

### ISSUE THREAD

**Issue by Sampssa** [Edenik/Flutter-Instagram-Clone#9]
@Edenik Posts are not showing on the Feed page. Can you please help me? I also get this error: 'package:instagram/utilities/repo_const.dart' doesn't exsist

**Comment by ahraf111** [comment]
@Edenik I'm facing the same error could you please help out with this.

**Comment by Edenik** [comment]
> @Edenik Posts are not showing on the Feed page. Can you please help me? I also get this error: 'package:instagram/utilities/repo_const.dart' doesn't exsist



> @Edenik I'm facing the same error could you please help out with this.

Have a look at this issue:
https://github.com/Edenik/InstaDart-Flutter-Instagram-Clone/issues/2

to get feed posts you must upload posts or follow users with posts.
